/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Chat: typeof import('./components/chat/chat.vue')['default']
    Container: typeof import('./components/Container.vue')['default']
    copy: typeof import('./components/Menu copy.vue')['default']
    Menu: typeof import('./components/Menu.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./components/chat/test.vue')['default']
    UserMenu: typeof import('./components/UserMenu.vue')['default']
  }
}
