/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AssistantMenu: typeof import('./components/AssistantMenu.vue')['default']
    Chat: typeof import('./components/chat/chat.vue')['default']
    ChatMenu: typeof import('./components/ChatMenu.vue')['default']
    Container: typeof import('./components/Container.vue')['default']
    LeftSettings: typeof import('./components/LeftSettings.vue')['default']
    Menu: typeof import('./components/Menu.vue')['default']
    MessageList: typeof import('./components/chat/MessageList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserMenu: typeof import('./components/UserMenu.vue')['default']
  }
}
