/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AccountSettings: typeof import('./components/settings/AccountSettings.vue')['default']
    AssistantMenu: typeof import('./components/AssistantMenu.vue')['default']
    AssistantSettings: typeof import('./components/settings/AssistantSettings.vue')['default']
    Chat: typeof import('./components/chat/Chat.vue')['default']
    ChatMenu: typeof import('./components/ChatMenu.vue')['default']
    ChatSettings: typeof import('./components/settings/ChatSettings.vue')['default']
    Layout: typeof import('./components/chat/Layout.vue')['default']
    LeftSettings: typeof import('./components/settings/LeftSettings.vue')['default']
    LibrarySettings: typeof import('./components/settings/LibrarySettings.vue')['default']
    Lottie: typeof import('./components/Lottie.vue')['default']
    Markdown: typeof import('./components/markdown/index.vue')['default']
    Mask: typeof import('./components/Mask.vue')['default']
    MemorySettings: typeof import('./components/settings/MemorySettings.vue')['default']
    Menu: typeof import('./components/Menu.vue')['default']
    MessageList: typeof import('./components/chat/MessageList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToolSettings: typeof import('./components/settings/ToolSettings.vue')['default']
    UserMenu: typeof import('./components/UserMenu.vue')['default']
  }
}
